version : "3"
services:
  web-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    
    
#   db:
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - '5432:5432'
#     volumes: 
#       - db:/var/lib/postgresql/data/
# volumes:
#   db:
#     driver: local